name: Deploy React SPA to Aliyun ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: main
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Verify rsync installation
        run: |
          which rsync
          rsync --version

      - name: Deploy to Aliyun Server
        uses: easingthemes/ssh-deploy@v4.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          RSYNC_PATH: /usr/bin/rsync  # 明确指定 rsync 路径
