name: Deploy React SPA to Aliyun ECS

on:
  push:
    branches: [ main ] # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: main
          submodules: true

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 根据项目需求选择 Node.js 版本

      # 3. 安装依赖
      - name: Install Dependencies
        run: npm install

      # 4. 构建 React 项目
      - name: Build
        run: npm run build

      # 5. 部署到阿里云 ECS
      - name: Deploy to Aliyun Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete" # 同步并删除目标目录中多余的文件
          SOURCE: "build/" # React 构建输出目录
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
